USE [master]
GO

/****** Object:  Database [ViewSimulation]    Script Date: 21/09/2015 9:50:07 p.m. ******/
CREATE DATABASE [ViewSimulation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ViewSimulation', FILENAME = N'C:\MSSQL\DATA\ViewSimulation.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ViewSimulation_log', FILENAME = N'C:\MSSQL\DATA\ViewSimulation_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ViewSimulation] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ViewSimulation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ViewSimulation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ViewSimulation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ViewSimulation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ViewSimulation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ViewSimulation] SET ARITHABORT OFF 
GO

ALTER DATABASE [ViewSimulation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ViewSimulation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ViewSimulation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ViewSimulation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ViewSimulation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ViewSimulation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ViewSimulation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ViewSimulation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ViewSimulation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ViewSimulation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ViewSimulation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ViewSimulation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ViewSimulation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ViewSimulation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ViewSimulation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ViewSimulation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ViewSimulation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ViewSimulation] SET RECOVERY FULL 
GO

ALTER DATABASE [ViewSimulation] SET  MULTI_USER 
GO

ALTER DATABASE [ViewSimulation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ViewSimulation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ViewSimulation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ViewSimulation] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ViewSimulation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ViewSimulation] SET  READ_WRITE 
GO


